### ISSUE TITLE
Design Template for getFormat

### ISSUE THREAD

**Issue by mahletm-777** [bkochuna/ners570f22-SpMV#18]
## Background
Explain why this issue was created/needed

We need to construct a design pattern and simplify the complexity of the interface by reducing the number of conversions between different formats.

## Tasks
Describe what work is expected to be performed as a part of this issue

Apply design patterns by constructing UML diagrams by producing class, sequence, state, and communication diagrams

## Definition of Done
Describe acceptance criteria for the issue

- [x] produce UML diagrams that outline the interface
- [x] having a working implementation high-level design

**Comment by bkochuna** [comment]
Hi @mahletm-777 we'll still need to finish filling out the description of this ticket. I think there are few things I can help to clarify.

The objective of this ticket is to develop the design for this. Therefore, part of the evidence of this task being performed is design documnetation (e.g. one or more UML diagrams).

In addition to the UML. You will also need to provide an implementation for the high-level design.

In other words, this issue is about completing a high level design for the code that satisfies the requirements that the client be able to get the matrix in a particular format.

I would expect the activities on this issue to include: prototyping some interfaces. deciding on the "best" interface. Produce some UML diagrams to document the design, and implement the high level "skeleton code" for the design.

This issue is not about implementing all the specific implementations of getFormat, or writing the test for it. We will create those as new issues following the completion of this issue.

**Comment by mahletm-777** [comment]
This is a possible design format:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/115249387/197672736-e2a26d47-8d80-4415-af8a-71398997b069.png">
